"""add call tracking tables

Revision ID: 91f7e164e5b2
Revises: d4f2e6c6346a
Create Date: 2026-06-04 17:41:04.941052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91f7e164e5b2'
down_revision: Union[str, Sequence[str], None] = 'd4f2e6c6346a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speaker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caller_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recording_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_recordings')
    op.drop_table('call_logs')
    op.drop_table('call_conversations')
    # ### end Alembic commands ###
